import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import ts from 'typescript';
import prettier from 'prettier';
import { createSourceProgram, listSources, loadManifest, moduleExports } from './source.mjs';

const root = path.resolve(import.meta.dirname, '../..');
const isCheck = process.argv.includes('--check');
const generatedBanner = '// Generated by tooling/component-contract/generate.mjs. Do not edit.\n';
const changedFiles = [];
const errors = [];

const read = (relativePath) => fs.readFile(path.join(root, relativePath), 'utf8');

async function pathExists(relativePath) {
	try {
		await fs.access(path.join(root, relativePath));
		return true;
	} catch (error) {
		if (error.code !== 'ENOENT') throw error;
		return false;
	}
}

async function sourceIndexes(directory) {
	const entries = await fs.readdir(path.join(root, directory), { withFileTypes: true });
	const indexes = [];
	for (const entry of entries) {
		const relativePath = path.posix.join(directory, entry.name);
		if (entry.isDirectory()) {
			indexes.push(...(await sourceIndexes(relativePath)));
		} else if (entry.name === 'index.ts') {
			indexes.push(relativePath);
		}
	}
	return indexes;
}

async function assertManifest(entries) {
	const files = await listSources(path.join(root, 'src/lib'));
	const manifestPath = path.join(root, 'tooling/component-contract/manifest.ts');
	const program = createSourceProgram([...files, manifestPath]);
	for (const diagnostic of program.getSemanticDiagnostics(program.getSourceFile(manifestPath)))
		errors.push(ts.flattenDiagnosticMessageText(diagnostic.messageText, '\n'));
	const ids = new Set();
	const subpaths = new Set();
	const routes = new Set();
	const docOwners = new Map();
	const registryOwners = new Map();
	const componentIds = new Set(
		entries.flatMap((entry) => [entry.id, ...entry.docs.map((doc) => doc.id)])
	);

	for (const entry of entries) {
		if (ids.has(entry.id)) errors.push(`Duplicate manifest id: ${entry.id}`);
		if (entry.subpath && subpaths.has(entry.subpath)) {
			errors.push(`Duplicate package subpath: ${entry.subpath}`);
		}
		ids.add(entry.id);
		if (entry.subpath) subpaths.add(entry.subpath);
		if (!entry.id || !entry.capabilities.length)
			errors.push(`Incomplete manifest entry: ${entry.id}`);
		if (entry.visibility === 'public' && (!entry.subpath || !entry.exports)) {
			errors.push(`Public entry ${entry.id} has no package target`);
		}
		if (entry.visibility === 'public' && entry.id !== 'package-json' && !entry.mcp)
			errors.push(`Missing public MCP description: ${entry.id}`);
		for (const id of new Set([entry.id, ...entry.docs.map((doc) => doc.id)])) {
			if (registryOwners.has(id))
				errors.push(`Conflicting registry id ${id}: ${registryOwners.get(id)} and ${entry.id}`);
			registryOwners.set(id, entry.id);
		}

		if (entry.sourceIndex.includes('*')) {
			const directory = entry.sourceIndex.slice(0, entry.sourceIndex.indexOf('*'));
			if (!(await pathExists(directory)))
				errors.push(`Missing wildcard source directory: ${directory}`);
		} else if (!(await pathExists(entry.sourceIndex))) {
			errors.push(`Missing source: ${entry.sourceIndex}`);
		}
		await assertSourceExports(entry, program, files);
		if (entry.exports) {
			const targets =
				typeof entry.exports === 'string' ? [entry.exports] : Object.values(entry.exports);
			for (const target of targets) {
				const expected =
					entry.sourceIndex === 'package.json'
						? './package.json'
						: `./dist/${entry.sourceIndex.slice('src/lib/'.length).replace(/\.ts$/, target.endsWith('.d.ts') ? '.d.ts' : '.js')}`;
				if (target !== expected)
					errors.push(`Broken package target for ${entry.id}: ${target}; expected ${expected}`);
			}
		}

		for (const doc of entry.docs) {
			if (!doc.label.trim() || !doc.category.trim() || !doc.id.trim())
				errors.push(`Incomplete documentation for ${entry.id}`);
			const docOwner = docOwners.get(doc.id);
			if (docOwner && docOwner !== entry.id) {
				errors.push(`Duplicate documentation id ${doc.id}: ${docOwner} and ${entry.id}`);
			}
			docOwners.set(doc.id, entry.id);
			if (routes.has(doc.route)) errors.push(`Duplicate documentation route: ${doc.route}`);
			routes.add(doc.route);
			const routeFile = `src/routes${doc.route}/+page.svelte`;
			if (!(await pathExists(routeFile))) errors.push(`Missing documentation route: ${routeFile}`);
		}

		if (entry.mcp) {
			const mcpSource = `src/lib/${entry.mcp.source.replace(/\.js$/, '.ts')}`;
			if (!(await pathExists(mcpSource))) {
				errors.push(`Missing MCP description source: ${mcpSource}`);
			} else {
				const symbol = moduleExports(program, path.join(root, mcpSource)).find(
					(symbol) => symbol.name === entry.mcp.exportName
				);
				if (!symbol) {
					errors.push(`Missing ${entry.mcp.exportName} export in ${mcpSource}`);
				} else {
					const declaration = symbol.valueDeclaration;
					const initializer =
						declaration && ts.isVariableDeclaration(declaration)
							? declaration.initializer
							: undefined;
					if (
						!initializer ||
						(ts.isStringLiteralLike(initializer) && !initializer.text.trim()) ||
						(!ts.isStringLiteralLike(initializer) && !ts.isTemplateExpression(initializer))
					) {
						errors.push(`Missing MCP description content: ${mcpSource}`);
					}
				}
			}
		}

		for (const relatedId of entry.relatedComponents) {
			if (!componentIds.has(relatedId)) {
				errors.push(`Unknown related component "${relatedId}" on ${entry.id}`);
			}
		}
	}

	const grid = entries.find((entry) => entry.id === 'grid');
	if (
		!grid ||
		grid.subpath !== './grid' ||
		!grid.exportedSymbols.includes('GridSpan') ||
		!grid.docs.some((doc) => doc.id === 'grid-span')
	) {
		errors.push('GridSpan must remain documented and exported from svelai/grid');
	}

	const modeledIndexes = new Set(entries.map((entry) => entry.sourceIndex));
	for (const sourceIndex of await sourceIndexes('src/lib')) {
		if (!modeledIndexes.has(sourceIndex)) {
			errors.push(`Unmodeled public source index: ${sourceIndex}`);
		}
	}
	for (const [consumer, module] of [
		['src/hooks.server.ts', '$lib/generated/componentMcpRegistry.js'],
		['src/routes/appNavigation.ts', './componentNavigation.generated.js']
	]) {
		const source = ts.createSourceFile(
			consumer,
			await read(consumer),
			ts.ScriptTarget.Latest,
			true
		);
		if (
			!source.statements.some(
				(statement) =>
					ts.isImportDeclaration(statement) &&
					ts.isStringLiteral(statement.moduleSpecifier) &&
					statement.moduleSpecifier.text === module
			)
		)
			errors.push(`${consumer} must consume generated ${module}`);
	}
}

async function assertSourceExports(entry, program, files) {
	if (!entry.exportedSymbols) {
		errors.push(`Missing exported-symbol contract: ${entry.id}`);
		return;
	}
	if (entry.sourceIndex === 'package.json') return;
	const wildcard = entry.sourceIndex.includes('*');
	const prefix = path.join(root, entry.sourceIndex.split('*')[0]).replace(/\/$/, '');
	const sources = wildcard
		? files.filter((filename) => filename.startsWith(prefix) && path.dirname(filename) === prefix)
		: [path.join(root, entry.sourceIndex)];
	if (wildcard && !sources.length) errors.push(`Empty wildcard source: ${entry.sourceIndex}`);
	for (const filename of sources) {
		if (!program.getSourceFile(filename)) continue;
		const moduleName = path.basename(filename, '.ts');
		const expected = Array.isArray(entry.exportedSymbols)
			? entry.exportedSymbols
			: (entry.exportedSymbols.modules[moduleName] ??
				entry.exportedSymbols.pattern.map((name) => name.replaceAll('{name}', moduleName)));
		const actual = moduleExports(program, filename).map((symbol) => symbol.name);
		if (new Set(expected).size !== expected.length)
			errors.push(`Duplicate exported symbols: ${entry.id}`);
		const missing = expected.filter((name) => !actual.includes(name));
		const unmodeled = actual.filter((name) => !expected.includes(name));
		if (missing.length || unmodeled.length)
			errors.push(
				`${path.relative(root, filename)}: exported-symbol drift; missing [${missing}], unmodeled [${unmodeled}]`
			);
		for (const declaration of program
			.getSourceFile(filename)
			.statements.filter(ts.isExportDeclaration)) {
			if (!declaration.moduleSpecifier || !ts.isStringLiteral(declaration.moduleSpecifier))
				continue;
			const specifier = declaration.moduleSpecifier.text;
			if (specifier.endsWith('.svelte') && specifier.startsWith('.')) {
				if (
					!(await pathExists(path.relative(root, path.resolve(path.dirname(filename), specifier))))
				)
					errors.push(`Broken component export: ${filename} -> ${specifier}`);
				continue;
			}
			const resolved = ts.resolveModuleName(
				specifier,
				filename,
				program.getCompilerOptions(),
				ts.sys
			).resolvedModule;
			if (!resolved)
				errors.push(`Broken export target: ${path.relative(root, filename)} -> ${specifier}`);
			else if (declaration.exportClause && ts.isNamedExports(declaration.exportClause)) {
				const targetSymbols = moduleExports(program, resolved.resolvedFileName).map(
					(symbol) => symbol.name
				);
				for (const element of declaration.exportClause.elements) {
					const imported = (element.propertyName ?? element.name).text;
					if (!targetSymbols.includes(imported))
						errors.push(
							`Broken export symbol: ${path.relative(root, filename)} -> ${specifier}#${imported}`
						);
				}
			}
		}
	}
}

function packageJsonOutput(entries, currentPackage) {
	const packageEntries = entries.filter((entry) => entry.subpath && entry.exports);
	const exports = Object.fromEntries(packageEntries.map((entry) => [entry.subpath, entry.exports]));
	const typePaths = Object.fromEntries(
		packageEntries.flatMap((entry) => {
			if (typeof entry.exports === 'string' || !entry.exports.types) return [];
			return [[entry.subpath.slice(2), [entry.exports.types.slice(2)]]];
		})
	);
	return `${JSON.stringify(
		{
			...currentPackage,
			exports,
			typesVersions: { '*': typePaths }
		},
		null,
		'\t'
	)}\n`;
}

function mcpRegistryOutput(entries) {
	const imports = [];
	const importNames = new Map();

	for (const entry of entries.filter((candidate) => candidate.mcp)) {
		const key = `${entry.mcp.source}:${entry.mcp.exportName}`;
		if (importNames.has(key)) continue;
		importNames.set(key, entry.mcp.exportName);
		imports.push(`import { ${entry.mcp.exportName} } from '$lib/${entry.mcp.source}';`);
	}

	const registryEntries = [];
	for (const entry of entries.filter((candidate) => candidate.mcp)) {
		const ids = new Set([entry.id, ...entry.docs.map((doc) => doc.id)]);
		for (const id of ids) {
			registryEntries.push(`\t${JSON.stringify(id)}: ${entry.mcp.exportName}`);
		}
	}

	return `${generatedBanner}${imports.join('\n')}\n\nexport const componentMcpRegistry = {\n${registryEntries.join(
		',\n'
	)}\n} as const;\n\nexport type ComponentMcpId = keyof typeof componentMcpRegistry;\n`;
}

function navigationOutput(entries) {
	const sections = [];
	const sectionByCategory = new Map();

	for (const entry of entries) {
		for (const doc of entry.docs) {
			let section = sectionByCategory.get(doc.category);
			if (!section) {
				section = { label: doc.category, links: [] };
				sectionByCategory.set(doc.category, section);
				sections.push(section);
			}
			section.links.push({ href: doc.route, text: doc.label });
		}
	}

	return `${generatedBanner}export const componentNavigationSections = ${JSON.stringify(
		sections,
		null,
		'\t'
	)} as const;\n`;
}

function metadataOutput(entries) {
	const inventory = entries.map((entry) => ({
		id: entry.id,
		subpath:
			entry.subpath === null
				? null
				: entry.subpath === './package.json'
					? 'svelai/package.json'
					: `svelai/${entry.subpath.slice(2)}`,
		sourceIndex: entry.sourceIndex,
		exportedSymbols: entry.exportedSymbols,
		docs: entry.docs,
		capabilities: entry.capabilities,
		relatedComponents: entry.relatedComponents,
		visibility: entry.visibility
	}));
	const related = Object.fromEntries(
		entries.flatMap((entry) => {
			const ids = new Set([entry.id, ...entry.docs.map((doc) => doc.id)]);
			return [...ids].map((id) => [id, entry.relatedComponents]);
		})
	);

	return `${generatedBanner}export const componentInventory = ${JSON.stringify(
		inventory,
		null,
		'\t'
	)} as const;\n\nexport const relatedComponents = ${JSON.stringify(
		related,
		null,
		'\t'
	)} as const;\n\nexport type ComponentInventoryEntry = (typeof componentInventory)[number];\n`;
}

function inventoryPageOutput() {
	return `<script lang="ts">
\timport { resolveLink } from '../appNavigation.js';
\timport { componentInventory } from '$lib/generated/componentContract.js';

\tconst publicEntries = componentInventory.filter((entry) => entry.visibility === 'public');
\tconst internalEntries = componentInventory.filter((entry) => entry.visibility === 'internal');
</script>

<svelte:head>
\t<title>Component inventory · svelai</title>
\t<meta
\t\tname="description"
\t\tcontent="The generated inventory of svelai components, utilities, entrypoints, and documentation."
\t/>
</svelte:head>

<article class="mx-auto flex w-full max-w-6xl flex-col gap-10">
\t<header class="flex max-w-3xl flex-col gap-3">
\t\t<p class="text-primary text-sm font-semibold">Public surface</p>
\t\t<h1 class="text-neutral text-4xl font-bold tracking-tight">Components and entrypoints</h1>
\t\t<p class="text-neutral/70 text-base">
\t\t\tThis inventory is generated from the package contract. It contains {publicEntries.length}
\t\t\tpublic entrypoints and {internalEntries.length} internal entrypoint.
\t\t</p>
\t</header>

\t<div class="border-neutral-muted overflow-hidden rounded-xl border">
\t\t<div
\t\t\tclass="bg-surface-recessed text-neutral/60 grid grid-cols-[minmax(12rem,1fr)_minmax(12rem,1fr)_auto] gap-4 border-b px-4 py-3 text-xs font-semibold uppercase tracking-wide"
\t\t>
\t\t\t<span>Entrypoint</span>
\t\t\t<span>Capabilities</span>
\t\t\t<span>Docs</span>
\t\t</div>
\t\t{#each componentInventory as entry (entry.id)}
\t\t\t<div
\t\t\t\tclass="border-neutral-muted grid grid-cols-[minmax(12rem,1fr)_minmax(12rem,1fr)_auto] items-center gap-4 border-b px-4 py-3 last:border-b-0"
\t\t\t>
\t\t\t\t<div class="flex min-w-0 items-center gap-2">
\t\t\t\t\t<code class="text-neutral truncate text-sm">{entry.subpath ?? 'Internal component'}</code>
\t\t\t\t\t{#if entry.visibility === 'internal'}
\t\t\t\t\t\t<span class="bg-warning-muted text-warning-dark rounded px-1.5 py-0.5 text-[0.625rem] font-semibold">
\t\t\t\t\t\t\tinternal
\t\t\t\t\t\t</span>
\t\t\t\t\t{/if}
\t\t\t\t</div>
\t\t\t\t<div class="flex flex-wrap gap-1.5">
\t\t\t\t\t{#each entry.capabilities as capability (capability)}
\t\t\t\t\t\t<span class="bg-surface-raised text-neutral/70 rounded-md px-2 py-1 text-xs">
\t\t\t\t\t\t\t{capability}
\t\t\t\t\t\t</span>
\t\t\t\t\t{/each}
\t\t\t\t</div>
\t\t\t\t<div class="flex flex-wrap justify-end gap-2">
\t\t\t\t\t{#each entry.docs as doc (doc.id)}
\t\t\t\t\t\t<a class="text-primary text-sm font-medium hover:underline" href={resolveLink(doc.route)}>{doc.label}</a>
\t\t\t\t\t{:else}
\t\t\t\t\t\t<span class="text-neutral/40 text-sm">—</span>
\t\t\t\t\t{/each}
\t\t\t\t</div>
\t\t\t</div>
\t\t{/each}
\t</div>
</article>
`;
}

function skillInventory(entries) {
	const categories = new Map();
	const modules = [];

	for (const entry of entries.filter((candidate) => candidate.visibility === 'public')) {
		if (entry.docs.length === 0) {
			modules.push(entry);
			continue;
		}
		for (const doc of entry.docs) {
			const category = categories.get(doc.category) ?? [];
			category.push({ entry, doc });
			categories.set(doc.category, category);
		}
	}

	const categorySections = [...categories]
		.map(
			([category, records]) =>
				`### ${category}\n\n${records
					.map(
						({ entry, doc }) =>
							`- \`${entry.subpath === './package.json' ? 'svelai/package.json' : `svelai/${entry.subpath.slice(2)}`}\` — ${doc.label} (${doc.route})`
					)
					.join('\n')}`
		)
		.join('\n\n');
	const moduleSection = modules
		.map(
			(entry) =>
				`- \`${entry.subpath === './package.json' ? 'svelai/package.json' : `svelai/${entry.subpath.slice(2)}`}\` — ${entry.capabilities.join(', ')}`
		)
		.join('\n');

	// Blank lines around the marker comments keep the block Prettier-stable.
	return `<!-- component-contract:inventory:start -->

## Generated Package Inventory

This section is generated from \`tooling/component-contract/manifest.ts\`.

${categorySections}

### Utilities and entrypoints

${moduleSection}

<!-- component-contract:inventory:end -->`;
}

function updateSkillInventory(source, inventory) {
	const start = '<!-- component-contract:inventory:start -->';
	const end = '<!-- component-contract:inventory:end -->';
	const startIndex = source.indexOf(start);
	const endIndex = source.indexOf(end);

	if (startIndex === -1 && endIndex === -1) return `${source.trimEnd()}\n\n${inventory}\n`;
	if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
		throw new Error('Malformed component contract inventory markers in svelai skill');
	}
	return `${source.slice(0, startIndex)}${inventory}${source.slice(endIndex + end.length)}`;
}

async function emit(relativePath, output) {
	if (!relativePath.endsWith('.md')) {
		const filepath = path.join(root, relativePath);
		output = await prettier.format(output, {
			...(await prettier.resolveConfig(filepath)),
			filepath
		});
	}
	let current = null;
	try {
		current = await read(relativePath);
	} catch (error) {
		if (error.code !== 'ENOENT') throw error;
	}

	if (current === output) return;
	changedFiles.push(relativePath);
	if (!isCheck) {
		await fs.mkdir(path.dirname(path.join(root, relativePath)), { recursive: true });
		await fs.writeFile(path.join(root, relativePath), output);
	}
}

const entries = await loadManifest();
await assertManifest(entries);
if (errors.length > 0) {
	console.error(errors.join('\n'));
	process.exit(1);
}

const packageJson = JSON.parse(await read('package.json'));
await emit('package.json', packageJsonOutput(entries, packageJson));
await emit('src/lib/generated/componentMcpRegistry.ts', mcpRegistryOutput(entries));
await emit('src/routes/componentNavigation.generated.ts', navigationOutput(entries));
await emit('src/lib/generated/componentContract.ts', metadataOutput(entries));
await emit(
	'src/lib/generated/componentAliases.js',
	`${generatedBanner}export const componentAliases = ${JSON.stringify(
		Object.fromEntries(
			entries
				.filter((entry) => entry.subpath && entry.sourceIndex !== 'package.json')
				// Vite uses the first matching prefix, so nested exports must come first.
				.sort((left, right) => right.subpath.split('/').length - left.subpath.split('/').length)
				.map((entry) => [
					`svelai/${entry.subpath.slice(2)}`,
					`./${entry.sourceIndex.replace(/\*\.ts$/, '*')}`
				])
		),
		null,
		'\t'
	)};\n`
);
await emit('src/routes/components/+page.svelte', inventoryPageOutput());

// `.claude/skills/svelai` is the canonical skill tree; `.agents/skills/svelai` is a
// generated mirror so both agent runtimes read identical docs.
const inventory = skillInventory(entries);
const canonicalSkillDir = '.claude/skills/svelai';
const mirrorSkillDir = '.agents/skills/svelai';
await emit(
	`${canonicalSkillDir}/SKILL.md`,
	updateSkillInventory(await read(`${canonicalSkillDir}/SKILL.md`), inventory)
);
for (const file of await fs.readdir(path.join(root, canonicalSkillDir))) {
	if (!file.endsWith('.md')) continue;
	await emit(`${mirrorSkillDir}/${file}`, await read(`${canonicalSkillDir}/${file}`));
}

if (isCheck && changedFiles.length > 0) {
	console.error(
		`Component contract drift detected:\n${changedFiles.map((file) => `- ${file}`).join('\n')}`
	);
	process.exit(1);
}

if (!isCheck && changedFiles.length > 0) {
	console.log(
		`Generated component contract:\n${changedFiles.map((file) => `- ${file}`).join('\n')}`
	);
}
