// Theme-part reference, one Markdown file per themeable component, generated from the same
// structure extractor the docs site's Theme tab uses. What a consumer needs to override a
// part without opening the source: which element it lands on, which variants it takes (and
// their default), and the exact classes each value contributes.
import fsSync from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import prettier from 'prettier';
import ts from 'typescript';

const root = path.resolve(import.meta.dirname, '../..');
export const themePartsDir = '.claude/skills/entasis/theme-parts';

// The extractor is TypeScript, shared with the Vite plugin. Transpile it into node_modules/.cache
// so its bare imports (ts-morph, svelte/compiler) keep resolving, then import it.
async function loadStructureMap() {
	const cacheDir = path.join(root, 'node_modules/.cache/entasis-structure');
	await fs.mkdir(cacheDir, { recursive: true });
	for (const name of ['extract', 'plugin']) {
		const source = await fs.readFile(path.join(root, `tooling/structure-docs/${name}.ts`), 'utf8');
		const { outputText } = ts.transpileModule(source, {
			compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 }
		});
		await fs.writeFile(
			path.join(cacheDir, `${name}.mjs`),
			outputText.replace(/from '\.\/(extract|types)\.js'/g, "from './$1.mjs'")
		);
	}
	await fs.writeFile(path.join(cacheDir, 'types.mjs'), 'export {};\n');
	const plugin = await import(
		`${pathToFileURL(path.join(cacheDir, 'plugin.mjs')).href}?t=${Date.now()}`
	);
	const { Project } = await import('ts-morph');
	return plugin.buildStructureMap(root, new Project({ skipAddingFilesFromTsConfig: true }));
}

const code = (text) => `\`${text}\``;

// Where a part lands, read from every non-test .svelte in the component's directory: the element
// whose `class={classes.<part>(..)}` it is, with its `data-slot` / `data-sidebar` hook when the
// tag carries one. Covers the parts a child component renders (Sidebar's rows, a Form's fields),
// which the main-file tree cannot see.
const elementsFor = (directory, part) => {
	const found = new Set();
	if (!directory) return found;
	const dir = path.join(root, 'src/lib/components', directory);
	for (const file of fsSync.readdirSync(dir)) {
		if (!file.endsWith('.svelte') || file.includes('.test.')) continue;
		const source = fsSync.readFileSync(path.join(dir, file), 'utf8');
		const use = new RegExp(`classes\\.${part}\\(`, 'g');
		for (let match; (match = use.exec(source));) {
			const open = source.lastIndexOf('<', match.index);
			if (open < 0) continue;
			const tagText = source.slice(open, match.index);
			if (tagText.includes('>')) continue;
			const tag = tagText.match(/^<([A-Za-z][\w:.-]*)/)?.[1];
			if (!tag) continue;
			const hook = tagText.match(/data-(?:slot|sidebar)="[^"]+"/)?.[0];
			found.add(hook ? `<${tag} ${hook}>` : `<${tag}>`);
		}
	}
	return found;
};
const tagsFor = (nodes, part, found = new Set()) => {
	for (const node of nodes ?? []) {
		if (node.themePart === part && node.tag) found.add(node.tag);
		tagsFor(node.children, part, found);
	}
	return found;
};

function render(structure) {
	const { name, registryKey, setter, importPath, parts, tree, directory } = structure;
	const lines = [
		`# ${registryKey ?? name} theme parts`,
		'',
		`Generated by \`npm run generate:component-contract\` from ${code(name)}'s theme file. Do not edit.`,
		'',
		`- Registry key: ${code(registryKey ?? '(none)')}, the key under \`<Theme components>\``,
		...(setter
			? [`- Setter: ${code(setter)}${importPath ? ` from ${code(importPath)}` : ''}`]
			: []),
		`- Parts: ${parts.length}. Each part takes \`base\` plus one map per variant in the \`theme\` prop, the setter and the registry alike.`,
		"- Override order: your classes land after the part's base, variant and compound classes, so a plain Tailwind class in an override's `base` beats any of them; the instance `class` prop lands last.",
		''
	];
	for (const part of parts) {
		lines.push(`## ${code(part.name)}`, '');
		if (part.kind === 'motion') {
			lines.push(
				`- Reserved \`motion\` slot, a transition spec rather than classes. Base: ${code(part.base ?? '{}')}`
			);
			for (const variant of part.variants ?? [])
				lines.push(
					`- ${code(variant.name)}: ${variant.options.map((o) => `${o.value} → ${code(o.classes || '{}')}`).join(' · ')}`
				);
			lines.push('');
			continue;
		}
		const elements = elementsFor(directory, part.name);
		for (const tag of tagsFor(tree, part.name))
			if (![...elements].some((e) => e.startsWith(`<${tag}`))) elements.add(`<${tag}>`);
		lines.push(
			`- Element: ${elements.size ? [...elements].map(code).join(' / ') : "not applied in this component's markup"}`
		);
		if (part.variants?.length) {
			lines.push(
				`- Variants: ${part.variants
					.map(
						(v) =>
							`${code(v.name)} (${v.options.map((o) => (o.value === part.defaultVariants?.[v.name] ? `**${o.value}**` : o.value)).join(' | ')})`
					)
					.join(' · ')} — bold is the default`
			);
		}
		lines.push(`- Base: ${part.base ? code(part.base) : '_none_'}`);
		for (const variant of part.variants ?? [])
			lines.push(
				`- ${code(variant.name)}: ${variant.options.map((o) => `${o.value} → ${o.classes ? code(o.classes) : '_none_'}`).join(' · ')}`
			);
		if (part.compoundVariants?.length)
			lines.push(
				`- Compound: ${part.compoundVariants
					.map(
						(c) =>
							`${Object.entries(c.when)
								.map(([k, v]) => `${k}=${v}`)
								.join(' & ')} → ${code(c.classes)}`
					)
					.join(' · ')}`
			);
		lines.push('');
	}
	return lines.join('\n');
}

/**
 * One file per component with a registry key, plus the keys that break the naming rule:
 * a registry key is the component's kebab-case name (`hover-card`, `ai-chat`), so a consumer
 * can write it from the import path without looking it up.
 */
export async function themePartsOutputs() {
	// The contract self-test runs the generator in a trimmed copy of the repo without the
	// extractor; in the real tree a missing extractor surfaces as 125 stale files in --check.
	if (!fsSync.existsSync(path.join(root, 'tooling/structure-docs/plugin.ts'))) {
		console.warn('theme-parts: tooling/structure-docs is absent, no reference generated');
		return { files: [], problems: [] };
	}
	const map = await loadStructureMap();
	const files = [];
	const problems = [];
	const seen = new Map();
	for (const structure of Object.values(map).sort((a, b) => a.name.localeCompare(b.name))) {
		if (!structure.registryKey) continue;
		if (seen.has(structure.registryKey))
			problems.push(
				`${structure.name}: registry key '${structure.registryKey}' is already used by ${seen.get(structure.registryKey)}`
			);
		seen.set(structure.registryKey, structure.name);
		if (!/^[a-z]+(-[a-z]+)*$/.test(structure.registryKey))
			problems.push(`${structure.name}: registry key '${structure.registryKey}' is not kebab-case`);
		const relativePath = `${themePartsDir}/${structure.registryKey}.md`;
		const filepath = path.join(root, relativePath);
		const content = await prettier.format(render(structure), {
			...(await prettier.resolveConfig(filepath)),
			filepath
		});
		files.push({ relativePath, content });
	}
	return { files, problems };
}
