<script lang="ts">
	import {
		AudioPlayer,
		type AudioPlayerControl,
		type AudioPlayerErrorPayload
	} from '$lib/components/AudioPlayer/index.js';
	import { FileInput } from '$lib/components/Form/File/index.js';

	const controls: AudioPlayerControl[] = [
		'play',
		'seekBackward',
		'seekForward',
		'time',
		'volume',
		'loop'
	];
	const maxFileSize = 100 * 1024 * 1024;

	let file = $state<File | null>(null);
	let audioSrc = $state<string | undefined>();
	let errorMessage = $state('');

	const title = $derived(file ? stripMp3Extension(file.name) : 'Dropped MP3');
	const artist = $derived(
		file ? `Local file - ${formatFileSize(file.size)}` : 'Autogenerated waveform'
	);

	$effect(() => {
		const currentFile = file;
		audioSrc = undefined;
		errorMessage = '';
		if (!currentFile) return;
		if (!isMp3File(currentFile)) {
			errorMessage = 'Select an MP3 file.';
			return;
		}

		const objectUrl = URL.createObjectURL(currentFile);
		audioSrc = objectUrl;
		return () => URL.revokeObjectURL(objectUrl);
	});

	function handleError({ error }: AudioPlayerErrorPayload) {
		errorMessage = error instanceof Error ? error.message : 'Audio playback failed.';
	}

	function isMp3File(candidate: File) {
		return candidate.type === 'audio/mpeg' || candidate.name.toLowerCase().endsWith('.mp3');
	}

	function stripMp3Extension(fileName: string) {
		return fileName.replace(/\.mp3$/i, '');
	}

	function formatFileSize(bytes: number) {
		if (bytes === 0) return '0 B';
		const units = ['B', 'KB', 'MB', 'GB'];
		const unitIndex = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
		const value = bytes / 1024 ** unitIndex;
		return `${value.toFixed(unitIndex === 0 ? 0 : 1)} ${units[unitIndex]}`;
	}
</script>

<div class="grid w-full gap-3">
	<FileInput
		label="MP3 file"
		mode="single"
		types={['audio/mpeg', '.mp3']}
		maxSize={maxFileSize}
		bind:value={file}
		placeholder="Drop an MP3 file or click to choose"
	/>

	{#if errorMessage}
		<p class="border-danger/30 bg-danger/10 text-danger rounded-md border px-3 py-2 text-sm">
			{errorMessage}
		</p>
	{/if}

	{#if audioSrc}
		<AudioPlayer
			src={audioSrc}
			{title}
			{artist}
			color="info"
			download={false}
			{controls}
			onError={handleError}
		/>
	{/if}
</div>
